import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import Banner from "../components/banner/banner.component";

import styles from "../styles/Home.module.css";

export default function Home() {
  const handleOnBannerBtnClick = () => {
    console.log("hi banner button");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <Link href="/dynamic">
          <a>Go to page dynamic</a>
        </Link>
      </main>
    </div>
  );
}
